# Generated by Django 5.0.2 on 2024-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitsinstock',
            field=models.IntegerField(default=3),
        ),
    ]
